### ISSUE TITLE
can not work in vite2.0?

### ISSUE THREAD

**Issue by ZedCoding** [lkxian888/postcss-px-to-viewport-8-plugin#1]
![image](https://user-images.githubusercontent.com/24578758/165919515-72a1c15d-336f-4140-b9b6-dc3d5b1c327e.png)

**Comment by lkxian888** [comment]
vite请在vite.config.ts 添加如下代码  
import postcsspxtoviewport8plugin from 'postcss-px-to-viewport-8-plugin';

export default defineConfig({
  css: {
    postcss: {
      plugins: [
        postcsspxtoviewport8plugin({
          unitToConvert: 'px', 
          viewportWidth: 1920;
          unitPrecision: 5, 
          propList: ['*'], 
          viewportUnit: 'vw', 
          fontViewportUnit: 'vw', 
          selectorBlackList: [], 
          minPixelValue: 1,
          mediaQuery: true, 
          replace: true, 
          exclude: [], 
          include: undefined, 
          landscape: false, 
          landscapeUnit: 'vw'
        }),
      ],
    },
  },
})
