### ISSUE TITLE
px 没有转换为rem

### ISSUE THREAD

**Issue by danyun123** [lkxian888/postcss-px-to-viewport-8-plugin#27]
这是配置文件
![image](https://github.com/lkxian888/postcss-px-to-viewport-8-plugin/assets/100011153/e7d1bc46-d59c-440c-9242-6e102978f21d)

只有这里的 paddingX 生效了
![image](https://github.com/lkxian888/postcss-px-to-viewport-8-plugin/assets/100011153/f8d16a58-547e-4615-85b4-94155703d6bd)

其他任何地方的属性都没有生效

![image](https://github.com/lkxian888/postcss-px-to-viewport-8-plugin/assets/100011153/f6982d76-872b-499a-bef0-dc9649334549)
![image](https://github.com/lkxian888/postcss-px-to-viewport-8-plugin/assets/100011153/6f22811b-596e-40d9-8970-05aacff5971b)

**Comment by lkxian888** [comment]
> 这是配置文件 ![image](https://user-images.githubusercontent.com/100011153/260939888-e7d1bc46-d59c-440c-9242-6e102978f21d.png)
> 
> 只有这里的 paddingX 生效了 ![image](https://user-images.githubusercontent.com/100011153/260940582-f8d16a58-547e-4615-85b4-94155703d6bd.png)
> 
> 其他任何地方的属性都没有生效
> 
> ![image](https://user-images.githubusercontent.com/100011153/260940224-f6982d76-872b-499a-bef0-dc9649334549.png) ![image](https://user-images.githubusercontent.com/100011153/260940404-6f22811b-596e-40d9-8970-05aacff5971b.png)

你样式为什么是.ts文件？

**Comment by lkxian888** [comment]
> > > 这是配置文件 ![image](https://user-images.githubusercontent.com/100011153/260939888-e7d1bc46-d59c-440c-9242-6e102978f21d.png)
> > > 只有这里的 paddingX 生效了 ![image](https://user-images.githubusercontent.com/100011153/260940582-f8d16a58-547e-4615-85b4-94155703d6bd.png)
> > > 其他任何地方的属性都没有生效
> > > ![image](https://user-images.githubusercontent.com/100011153/260940224-f6982d76-872b-499a-bef0-dc9649334549.png) ![image](https://user-images.githubusercontent.com/100011153/260940404-6f22811b-596e-40d9-8970-05aacff5971b.png)
> > 
> > 
> > 你样式为什么是.ts文件？
> 
> 因为我用的是Style-components 啊

可能不支持 .js/.ts文件，你可以在viewportWidth打印一下，看看终端有没有输出对应的样式文件路径出来，
 viewportWidth: file => {
         console.log(file)
            let num = 1920;
            return num;
          },
