### ISSUE TITLE
大哥，1.1.4发版都不带检查的么？？？

### ISSUE THREAD

**Issue by jiadesen** [lkxian888/postcss-px-to-viewport-8-plugin#4]
这种低级错误，懒得描述，自己装下看看吧，大无语。。。

**Comment by jiadesen** [comment]
改用 `postcss-pixel-to-remvw` 了

**Comment by lkxian888** [comment]
> 低级错误，懒得描述，自己装下看看吧，大无语。。。

抱歉，已修复

**Comment by jiadesen** [comment]
动态配置 `viewportWidth` 这个特性很不错，建议文档也跟上
