### ISSUE TITLE
安卓机型、微信浏览器出现适配问题

### ISSUE THREAD

**Issue by Aresnine** [lkxian888/postcss-px-to-viewport-8-plugin#43]
电脑端一切使用正常，苹果手机展示效果也没有问题，但是安卓端的设备出现了转换问题

**Comment by lkxian888** [comment]
这是编译后就已经转换了单位，和机型没关系的

**Comment by lkxian888** [comment]
> 电脑端一切使用正常，苹果手机展示效果也没有问题，但是安卓端的设备出现了转换问题

这是编译后就已经转换了单位，和机型没关系的
