### ISSUE TITLE
errore

### ISSUE THREAD

**Issue by xiaobo1215** [lkxian888/postcss-px-to-viewport-8-plugin#5]
![image](https://user-images.githubusercontent.com/20086016/185574139-3430c92b-897e-4cb5-b9ff-244190097482.png)

![Uploading image.png…]()

图一中 不应该 用 new

**Comment by xiaobo1215** [comment]
![image](https://user-images.githubusercontent.com/20086016/185574675-56b6b4b4-9841-44d0-8671-714e61540633.png)

**Comment by lkxian888** [comment]
> ![image](https://user-images.githubusercontent.com/20086016/185574675-56b6b4b4-9841-44d0-8671-714e61540633.png)
好的，感谢纠正
