### ISSUE TITLE
1.1.8 更新了啥，直接不能用了

### ISSUE THREAD

**Issue by jiadesen** [lkxian888/postcss-px-to-viewport-8-plugin#7]
Error: Loading PostCSS Plugin failed: Cannot use import statement outside a module

**Comment by lkxian888** [comment]
已修复，麻烦更新至1.1.9版本使用

**Comment by jiadesen** [comment]
还是不行

```
Error: Loading PostCSS Plugin failed: req(...) is not a function
```

**Comment by lkxian888** [comment]
@jiadesen 麻烦贴下你的代码使用方式

**Comment by jiadesen** [comment]
<img width="694" alt="image" src="https://user-images.githubusercontent.com/22772994/217460037-76818f1c-3cba-4c99-8571-710024484194.png">

**Comment by hlbj105** [comment]
> 还是不行
> 
> ```
> Error: Loading PostCSS Plugin failed: req(...) is not a function
> ```

我的也报这个了

```
module.exports = {
  plugins: {
    'postcss-px-to-viewport-8-plugin': {
      // 设计稿宽度
      viewportWidth: 750,
      exclude: [/node_modules/],
      // 需要转换的单位，默认为"px"
      unitToConvert: 'rpx',
    },
  },
};

```

**Comment by jiadesen** [comment]
@lkxian888 建议不要只在本地进行发版操作，及时提交一下，这样有问题我们也方便帮你排查...

**Comment by lkxian888** [comment]
奇怪，在我本地也这样使用测试没问题，
已提交代码，那麻烦@jiadesen 放到你项目看看

**Comment by hlbj105** [comment]
> 

我这边用你发git最新的编译后，还是一样报错，会不会是postcss版本影响？
```
  "postcss": "^8.4.21",
    "postcss-html": "^1.5.0",
    "postcss-px-to-viewport-8-plugin": "^1.1.9",
```

**Comment by lkxian888** [comment]
@hlbj105 有demo给我测试下吗

**Comment by hlbj105** [comment]
> @hlbj105 有demo给我测试下吗

@lkxian888  这个demo你试试 https://gitee.com/hlbj105/postcss-px-to-viewport-8-plugin-demo

**Comment by lkxian888** [comment]
@hlbj105 麻烦vite用户，在vite.config.ts  添加下面代码
import postcssPxToViewport8Plugin from 'postcss-px-to-viewport-8-plugin';


 css: {
      postcss: {
        plugins: [
          postcssPxToViewport8Plugin({
            // 设计稿宽度
            viewportWidth: 750,
            exclude: [/node_modules/],
            // 需要转换的单位，默认为"px"
            unitToConvert: 'px',
          }),
        ],
      },
    },

**Comment by lkxian888** [comment]
@jiadesen 大佬，有demo给我测试下吗

**Comment by jiadesen** [comment]
我的也是 vite 项目，放在 `vite.config` 里是没问题，但是还是希望把 postcss 相关的配置集中放到 `postcss.config` 里，而且 vite 文档也说明了，如果不配置 `css.postcss`，就会去找项目内的 PostCSS 配置源，但是如果配置了，就不会再找，这点容易出问题，详见：[vite#css-postcss 说明](https://cn.vitejs.dev/config/shared-options.html#css-postcss)

**Comment by lkxian888** [comment]
> 我的也是 vite 项目，放在 `vite.config` 里是没问题，但是还是希望把 postcss 相关的配置集中放到 `postcss.config` 里，而且 vite 文档也说明了，如果不配置 `css.postcss`，就会去找项目内的 PostCSS 配置源，但是如果配置了，就不会再找，这点容易出问题，详见：[vite#css-postcss 说明](https://cn.vitejs.dev/config/shared-options.html#css-postcss)

好的，晚点会修复哈，postcss.config 是采用 CommonJs 引入模块，我改了 Es6 模块导出，才出现这个问题

**Comment by lkxian888** [comment]
@jiadesen @hlbj105 两位大佬，已修复，请更新至 1.2.0 版本
